### PR TITLE
Rework the DB api access

### PR DESCRIPTION
**Pull request by ksol**
per-commit review is slightly more readable.

This PR reworks the db api architecture, mostly by removed the "global" access there was. Before this PR, the DB Api was exposed at the same "level" of other API clients, but it's not a good fit: all other APIs require authenticating as a user (except for guest endpoints), while the DB api require authenticating as a user *then* as a specific database.

To accomodate this change, api clients need to keep track of which region they're targetting (this allows a regional API client to instantiate the db api client in the same region; the response for `token` doesn't relay that information).

Slight rename of files/classes as well.

### CODE REVIEW

**Review by aurelien-reeves-scalingo — CHANGES_REQUESTED** [review]
Looks good

Update of the Readme is missing

And an entry in the *unreleased* section of the changelog could be nice as this is a huge breaking change.

**Comment by ksol** [comment]
Updated the changelog. Can the readme wait a little bit? I have other PRs incoming and would rather change it all at once

**Review by aurelien-reeves-scalingo — APPROVED** [review]
It's important not to forget about it as this is a pretty big change.
I think it could even be nice to have an "upgrade guide"

**Comment by ksol** [comment]
>  I think it could even be nice to have an "upgrade guide"

If there's a demand for it. The download statistics of the gem are low enough that it might be worth spending the time on it

**Pull request merged**
